language: node_js
node_js:
- v5
branches:
  only: master
before_script:
- git config --global user.email "email@denysdovhan.com"
- git config --global user.name "Travis Builder"
- git remote rm origin
- git remote add origin https://denysdovhan:${GH_TOKEN}@github.com/denysdovhan/slides-what-is-bash.git
script:
- npm run deploy
env:
  global:
    secure: DOXTUJzUGu8Y7YwCH5bCY2/YuZ3z1wo6uaEP0XkddSyrSVt+zjUdIiahaSxId5zozgaicThI/7gqUZyidEv1yL2uZu1rvBEf5HwcGM/ivI0ufb1Y1YAknUbAxXJ8hxa3e6f0UqIf9AN2F+fXfpKZKeO9bdeCtrKnQIOdRy6JG6R0z6yOh5am5kD0k5s1Qs0Rm5iCCfn6pp+hTzr7tbGP0GqpNxTxmpGbDMtEyYDdGSaZp0+A6ZG29rwH4TvO+wQQrosakyA1Q1MNzsjSP3b2w9QCBiHOvF6nYmJsFz9aus736ChYjDSoudqIFHtcSBq7j2Pxk0jXjaZtERDZl/vuPo8xdXjcXtVKH+UJq2yTxBMGrGwaJc6oZ3fr9yPkmPIAJn7wM4KUMpZhoAQkAAS2ZfOQMgcH+uUQAR3a2+B/Gkh2rTDk54EEgjd0e6ENFIeFgQtRmLhBckGzuTSs1yaPXWhX3A6s22JcOvgVphwXeCnwRB/Q3qEfJu1ZwniWJ7k0kQ1oF6E9pkIq/ZJr9d/j2ffi6qmLDuMLmVcwqi6gv8W0KAu7CQ39xKeLbJoZu34hAoEkoWCIB2OpSlGDRrCKtKCHCh57HpAM9YTW3Cm4Z0coDRzxOom/Ko5uJb1KxAcyUjad4VjCPTtSVryG5gWDy//tTW0kECbXqMp9f0friVs=
